RecipeRazor/Pages/CategoriesPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RecipeRazor.Models;

namespace RecipeRazor.Pages
{
    public class CategoriesPageModel : PageModel
    {
        private readonly IHttpClientFactory _httpClientFactory;
        public CategoriesPageModel(IHttpClientFactory httpClientFactory) => _httpClientFactory = httpClientFactory;

        [BindProperty]
        public List<string> categories { get; set; } = new();

        public async Task<IActionResult> OnPostDelete(string deletedValue)
        {
            var client = _httpClientFactory.CreateClient("Recipes");
            categories = await client.GetFromJsonAsync<List<string>>("categories");
            var response = await client.DeleteAsync($"recipes/remove-category/{categories[Int32.Parse(deletedValue)]}");
            System.Threading.Thread.Sleep(1500);
            return RedirectToPage("./CategoriesPage");
        }
        public async Task<IActionResult> OnGet()
        {
            var client = _httpClientFactory.CreateClient("Recipes");
            categories = await client.GetFromJsonAsync<List<string>>("categories");
            return Page();
        }

        public async Task<IActionResult> OnPostUpdate(string newCategory, string oldValue)
        {
            var client = _httpClientFactory.CreateClient("Recipes");
            categories = await client.GetFromJsonAsync<List<string>>("categories");
            var response = await client.PutAsync($"recipes/rename-category?oldName={categories[Int32.Parse(oldValue)]}&newName={newCategory}", null);
            System.Threading.Thread.Sleep(1500);
            return RedirectToPage("./CategoriesPage");
        }
    }
}

RecipeRazor/Pages/EditRecipes.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RecipeRazor.Models;

namespace RecipeRazor.Pages
{
    public class EditRecipesModel : PageModel
    {
        private readonly IHttpClientFactory _httpClientFactory;
        public EditRecipesModel(IHttpClientFactory httpClientFactory) => _httpClientFactory = httpClientFactory;

        [BindProperty]
        public List<Recipe> recipesList { get; set; } = new List<Recipe>();
        public List<string> isError { get; set; } = new();
        public async Task OnGet(List<string> messages)
        {
            var client = _httpClientFactory.CreateClient("Recipes");
            recipesList = await client.GetFromJsonAsync<List<Recipe>>("recipes");
            isError = messages;
        }

        public async Task<IActionResult> OnPostUpdate(Guid id, string choiceEdit, string afterEdit)
        {
            var client = _httpClientFactory.CreateClient("Recipes");
            if (choiceEdit != null && afterEdit != null)
            {
                string temp = choiceEdit.Trim();
                string tmp2 = afterEdit.Trim();
                if (temp.Length != 0 && tmp2.Length != 0)
                {
                    var response = await client.PutAsync($"recipes/edit-recipe/{id}?attributeName={choiceEdit}&editedParameter={afterEdit}", null);
                    if (response.IsSuccessStatusCode)
                    {
                        isError = new List<string> { };
                        isError.Add("a");
                        isError.Add("b");
                    }
                }
                else
                {
                    isError = new List<string> { };
                    isError.Add("1");
                    isError.Add("2");
                }
            }
            else
            {
                isError = new List<string> { };
                isError.Add("1");
                isError.Add("2");
            }
            return RedirectToPage("./EditRecipes", new { messages = isError });
        }

    }
}

RecipeRazor/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace RecipeRazor.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

RecipeRazor/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RecipeRazor.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

RecipeRazor/Pages/List.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RecipeRazor.Models;

namespace RecipeRazor.Pages
{
    public class ListModel : PageModel
    {
        private readonly IHttpClientFactory _httpClientFactory;
        public ListModel(IHttpClientFactory httpClientFactory) => _httpClientFactory = httpClientFactory;

        [BindProperty]
        public Recipe recipe { get; set; }
        public IEnumerable<Recipe> foundRecipe { get; set; } = new List<Recipe>();
        public string numberOfResults { get; set; } = "";

        public async Task<IActionResult> OnPost()
        {
            var client = _httpClientFactory.CreateClient("Recipes");
            try
            {
                await client.GetFromJsonAsync<List<Recipe>>($"recipes/list-recipe/{recipe.Title}");
            }
            catch
            {
                numberOfResults = "no results";
                return Page();
            }
            foundRecipe = await client.GetFromJsonAsync<List<Recipe>>($"recipes/list-recipe/{recipe.Title}");
            int num = foundRecipe.Count();
            numberOfResults = num.ToString();
            return Page();
        }
    }
}

RecipeRazor/Pages/RecipesPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RecipeRazor.Models;
using FluentValidation.Results;
namespace RecipeRazor.Pages;

public class RecipesPageModel : PageModel
{
    private readonly IHttpClientFactory _httpClientFactory;
    public RecipesPageModel(IHttpClientFactory httpClientFactory) => _httpClientFactory = httpClientFactory;

    // Allows us to create recipes from our custom recipe view.
    [BindProperty]
    public Recipe recipe { get; set; }
    public List<string> categ { get; set; } = new List<string>();
    public List<string> alerts = new();
    public async Task OnGet(List<string> messages)
    {
        var client = _httpClientFactory.CreateClient("Recipes");
        categ = await client.GetFromJsonAsync<List<string>>("categories");
        alerts = messages;
    }
    public async Task<IActionResult> OnPost(List<string> data)
    {
        var client = _httpClientFactory.CreateClient("Recipes");
        WebApplication3.Models.RecipesValidator validator = new();
        recipe.Categories = data;
        ValidationResult results = validator.Validate(recipe);
        if (results.IsValid)
        {
            recipe.Ingredients = recipe.Ingredients[0].Split("\r\n").ToList();
            recipe.Instructions = recipe.Instructions[0].Split("\r\n").ToList();
            var response = await client.PostAsJsonAsync("recipes/add-recipe", recipe);
            if (!response.IsSuccessStatusCode)
            {
                alerts.Add("error");
            }
            else
            {
                alerts.Add("no error");
            }
        }
        else
        {
            alerts.Add("error");
        }
        return RedirectToPage("./RecipesPage", new { messages = alerts });
    }
}

RecipeRazor/Pages/CategoriesPage.cshtml
@page
@model RecipeRazor.Pages.CategoriesPageModel
@{

    ViewData["Title"] = "categories";
}
<style>
    body {
        background: no-repeat;
        background-size: cover;
        height: 960px;
    }
</style>

<script type="text/javascript">
    function update(el) {
        $('input[name=oldValue]').val(($(el).closest('tr').index()).toString());
    }
    function remove(el) {
        $('input[name=deletedValue]').val(($(el).closest('tr').index()).toString());
    }
</script>

<script type="text/javascript">
    const imgs = [];
    imgs[0] = 'https://images.unsplash.com/photo-1632431455870-65dd9cf75e0e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1332&q=80';
    imgs[1] = 'https://images.unsplash.com/photo-1632436638809-f89272c90f64?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1332&q=80';
    imgs[2] = 'https://images.unsplash.com/photo-1633378217782-cbee9b307853?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1332&q=80';
    imgs[3] = 'https://images.unsplash.com/photo-1495195129352-aeb325a55b65?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1176&q=80';
    imgs[4] = 'https://images.unsplash.com/photo-1495195134817-aeb325a55b65?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1776&q=80';
    imgs[5] = 'https://images.unsplash.com/photo-1619367302084-3d07eb49159f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80';

    window.onload = function () {
        const random = Math.floor(Math.random() * imgs.length);
        document.body.style.backgroundImage = `url(${imgs[random]})`;
    }
</script>

<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script type="text/javascript">
    function myfunction() {
        Swal.fire({
            title: 'Are you sure you want to delete this category?',
            showDenyButton: true,
            confirmButtonText: 'Yes',
            confirmButtonColor: '#198754',
            denyButtonText: `No`,
        }).then((result) => {
            if (result.isConfirmed) {
                document.getElementById("updateButton").click();
                Swal.fire({
                    icon: 'success',
                    title: 'Successfully deleted!',
                    showConfirmButton: false,
                });
            }
            else if (result.isDenied) {
                Swal.fire('No changes are applied', '', 'info')
            }
        })
    }
    function updatefunc() {
        Swal.fire({
            icon: 'success',
            title: 'Successfully edited!',
            showConfirmButton: false,
        });
    }
</script>

<body>
    <h4 class="display-2 font-weight-bold ">Categories</h4>
    <br />
    <center>
        <table style="width:500px;" id="add_table" class=" bg-light table" data-toggle="table" data-mobile-responsive="true">
            <thead>
                <tr>
                    <th>Categories</th>
                    <th>Rename</th>
                    <th>Remove</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var category in Model.categories)
                {
                    <tr>
                        <td>
                            <input name="oldCategory" type="text" value="@category" id="original" />
                        </td>
                        <td>
                            <button type="button" onclick="update(this)" class="btn  btn btn-success add" id="btn" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                    <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                                </svg>
                            </button>
                        </td>
                        <td>
                            <form method="post" asp-page-handler="delete">
                                <button type="button" class="btn  btn btn-danger delete_row" name="isWorking" onclick="myfunction();remove(this)">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                                    </svg>
                                </button>
                                <button type="submit" id="updateButton" hidden></button>
                                <input type="hidden" name="deletedValue" />
                            </form>
                        </td>
                    </tr>

                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <form method="post" asp-page-handler="update">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Edit category</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <input type="hidden" name="oldValue" />
                                        <label for="edited">Category</label> &nbsp
                                        <input type="text" name="newCategory" placeholder="enter the new value.." id="edited" />
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        <button onclick="updatefunc()" data-bs-dismiss="modal" type="submit" class="btn btn-primary">Save changes</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                }
            </tbody>
        </table>
    </center>
</body>

RecipeRazor/Pages/EditRecipes.cshtml
@page
@model RecipeRazor.Pages.EditRecipesModel
@{
}
<script type="text/javascript">
    const imgs = [];
    imgs[0] = 'https://images.unsplash.com/photo-1632431455870-65dd9cf75e0e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1332&q=80';
    imgs[1] = 'https://images.unsplash.com/photo-1632436638809-f89272c90f64?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1332&q=80';
    imgs[2] = 'https://images.unsplash.com/photo-1633378217782-cbee9b307853?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1332&q=80';
    imgs[3] = 'https://images.unsplash.com/photo-1495195129352-aeb325a55b65?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1176&q=80';
    imgs[4] = 'https://images.unsplash.com/photo-1495195134817-aeb325a55b65?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1776&q=80';
    imgs[5] = 'https://images.unsplash.com/photo-1619367302084-3d07eb49159f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80';

    window.onload = function () {
        const random = Math.floor(Math.random() * imgs.length);
        document.body.style.backgroundImage = `url(${imgs[random]})`;
    }
</script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

@if (@Model.isError.Any())
{
    @foreach (var msg in Model.isError)
    {
        @if (msg == "1" || msg == "2")
        {
            <script type="text/javascript">
                Swal.fire({
                    icon: 'error',
                    title: 'Failed to edit',
                    text: 'make sure you pick an attribute and a new value.',
                    confirmButtonColor: '#198754'
                })
            </script>
        }
        @if (msg == "a" || msg == "b")
        {
            <script type="text/javascript">
                Swal.fire({
                    icon: 'success',
                    title: 'Successfully edited!',
                    showConfirmButton: true,
                    confirmButtonColor: '#198754'
                });
            </script>
        }
    }
}

<body style="size: 1040px; height: 960px; background: url('https://images.unsplash.com/photo-1495195134817-aeb325a55b65?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1776&q=80') no-repeat; background-size: cover ">
    <h1>Edit Recipe</h1>
    <table style="width:700px;" id="add_table" class=" bg-light table" data-toggle="table" data-mobile-responsive="true">
        <thead>
            <tr>
                <th>#</th>
                <th>Recipe title</th>
                <th>Recipe details</th>
                <th>Edit</th>
            </tr>
        </thead>
        <tbody>
            @{int i = 1;}
            @foreach (var recipe in Model.recipesList)
            {
                <tr>
                    <th scope="row">@(i++)</th>
                    <td>
                        <input name="oldCategory" type="text" value="@recipe.Title" id="original" />
                    </td>
                    <td>
                        <button type="button" onclick="update(this)" class="btn  btn btn-primary add" data-bs-toggle="modal" data-bs-target="#@("id"+recipe.Id)">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-circle" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                                <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
                            </svg>
                        </button>
                        <button type="submit" id="details" name="details" hidden></button>
                        <input type="hidden" id="info" name="info" />
                    </td>
                    <td>
                        <button type="button" class="btn  btn btn-success add" id="btn" data-bs-toggle="modal" data-bs-target="#@("m"+recipe.Id)">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                            </svg>
                        </button>
                    </td>
                </tr>
                <div class="modal fade" id="@("m"+recipe.Id)" tabindex="-1" aria-labelledby="exampleTwoModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title text-success" id="exampleModalLabel">Edit recipe</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <form method="post" asp-page-handler="update">
                                <div class="modal-body">
                                    <div class="mb-3">
                                        <label class="fw-bold">Pick the attribute to edit:</label><br>
                                        <input type="radio" id="title" name="choiceEdit" value="Title">
                                        <label for="title">Title</label><br>
                                        <input type="radio" id="ingredients" name="choiceEdit" value="Ingredients">
                                        <label for="ingredients">Ingredients</label><br>
                                        <input type="radio" id="instructions" name="choiceEdit" value="Instructions">
                                        <label for="instructions">Instructions</label><br>
                                        <input type="radio" id="categories" name="choiceEdit" value="Categories">
                                        <label for="categories">Categories</label><br><br>
                                        <label class="fw-bold" for="new">Enter the new value:</label>
                                        <br>
                                        <textarea style="width:470px;" id="new" name="afterEdit"></textarea>
                                        <br><br>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="submit" name="id" value="@recipe.Id" class="btn btn-primary" data-bs-dismiss="modal">Edit</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

                <div class="modal fade" id="@("id"+recipe.Id)" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">

                    <div class="modal-dialog modal-dialog-scrollable">
                        <div class="modal-content">
                            <form>
                                <div class="modal-header">
                                    <h5 class="modal-title text-success" id="exampleModalLabel">Recipe details</h5>
                                </div>
                                <div class="modal-body">
                                    <div class="mb-3">
                                        <label for="recipient-name" class="fw-bold col-form-label">Title</label>
                                        <input type="text" class="form-control" id="recipient-name" value="@recipe.Title">
                                    </div>
                                    <div class="mb-3">
                                        <label for="message-text" class="fw-bold col-form-label">Ingredients</label>
                                        <ul name="oooo">
                                            @foreach (var ingredient in recipe.Ingredients)
                                            {
                                                <li name="message-text"> @ingredient </li>
                                            }
                                        </ul>
                                    </div>
                                    <div class="mb-3">
                                        <label for="message-text" class="fw-bold col-form-label">Instructions</label>
                                        <ul>
                                            @foreach (var instruction in recipe.Instructions)
                                            {
                                                <li name="message-text"> @instruction </li>
                                            }
                                        </ul>
                                    </div>
                                    <div class="mb-3">
                                        <label for="message-text" class="fw-bold col-form-label">Categories</label>
                                        <ul>
                                            @foreach (var category in recipe.Categories)
                                            {
                                                <li name="message-text"> @category </li>
                                            }
                                        </ul>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            }
        </tbody>
    </table>
</body>


RecipeRazor/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<body style="size: 1040px; height: 960px; background: url('https://images.unsplash.com/photo-1495195134817-aeb325a55b65?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1776&q=80') no-repeat; background-size: cover ">
</body>
<div class="text-center">
    <br />
    <br />
    <br />
    <br />
    <h1 class="display-1 font-weight-bold">Welcome to</h1>
    <h4 class="display-2 font-weight-bold text-primary">AllRecipes</h4>
    <h6 class="text-size-16 text-weight-400 lh-copy text-align-center text-medium mb40">
        Search for, add, and edit recipes and modify categories
    </h6>
</div>